### ISSUE TITLE
Some renaming suggestions

### ISSUE THREAD

**Issue by Jutho** [maartenvd/MPSKit.jl#1]
Hi Maarten,

would you be open to some suggestions for renaming things.

* all names with `Mps` and `Mpo` to `MPS` and `MPO`
* `MPSCenterGauged` to just `InfiniteMPS`, the details of how this is stored/represented are not really relevant to most users I assume
* Is it possible to fuse `FiniteMPS` and `MPSComoving`? The ground state and time evolution algorithms anyway accept `Union{FiniteMPS,MPSComoving}`

Is there an advantage to having `FiniteMPS <: AbstractArray`?

I can prepare a PR somewhere next week.

**Comment by maartenvd** [comment]
Hi Jutho,

I agree with most of these, but I don't know if finitemps and mpscomoving should be fused. (mpscomoving should at any rate be renamed to something more sensible)

- A finiteMps starting with a virtual bond dimension > 1 makes no sense - so I wanted to enforce this in the constructor / setindex!. This conflicts with mpscomoving where this is perfectly possible.
- The plan was to implement window - moving algorithms somewhere, allowing you to track a propagating signal (needs access to the groundstates left - right of the window)
- There are some subtleties in the energy - density definition. The sum of the energy-densities for an mpscomoving does not correrspond to the actual energy change of the state it was embedded in (consider interaction terms larger then the window).

We can merge it, but we'd have to think about how to handle the energy density. At the moment I return a tuple for mpscomoving. The per-site groundstate density you would find when calculating the energy density in InfiniteMPS; and the total energy you would find when calculating for example propagator poles.

The abstractarray subtyping was just so that slicing automatically got defined.

I'll already start with renaming Mps/Mpo to MPS/MPO and MPSCenterGauged to InfiniteMPS
