### ISSUE TITLE
setindex should modify centerpos 

### ISSUE THREAD

**Issue by maartenvd** [maartenvd/MPSKit.jl#5]
when changing the data in a finitemps/finitempo/mpscomoving we should modify centerpos...

**Comment by maartenvd** [comment]
(this is what makes dmrg fail - when changing the bond dimension we end up with a left-orthonormalizd state but - according to centerpos - it is still righorthed; so rightorth!() does nothing)

**Comment by Jutho** [comment]
Yes that's why I said my implementation was unfinished :-). What I had in mind was that instead of `psi[n]`, there would be some `psi.AL[n]`, `psi.AC[n]`, `psi.AR[n]` and possibly `psi.C[n]`, but without all of these explicitly being stored, using `getproperty` and some dummy type that wraps the MPS, and then fixes the norm appropriately . This would then be very similar to the `InfiniteMPS` case, where those are explicitly stored.

**Comment by maartenvd** [comment]
Ah ok, the reason I initially didn't want to store something like centerpos was that it'd become quite cumbersome to have to movecenter! everytime you modify something - and it quickly becomes easy to introduce either errors / very verbose syntax / double work.

I really like the psi.(AL/AR/AC/C) idea

There's another question I had; should we introduce AbstractMPO or merge both of them into something like AbstractState?
